name: frontend-termometro-lasm
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - termometro-lasm
networks:
  termometro-lasm:
    external: true
